name: flutter_fluid_markdown
description: "A Flutter plugin to render Markdown with a fluid and beautiful user interface. This is a placeholder package."
version: 0.0.1
homepage: 'https://github.com/aichiko0225/flutter_fluid_markdown'
repository: 'https://github.com/aichiko0225/flutter_fluid_markdown'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tsystems.flutter_fluid_markdown
        pluginClass: FlutterFluidMarkdownPlugin
      ios:
        pluginClass: FlutterFluidMarkdownPlugin